name: Wes C Photography
favicon: null
layout_spectrum: 0.25281
typography_spectrum: 0.7316055574920028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9838529415428638
  lightness: 0.8534676001872867
  saturation: 0.056929151993244886
  rhythmicContrast: 0.4173704681452364
purpose: []
