name: Wes C Photography
favicon: null
layout_spectrum: 0.73958
typography_spectrum: 0.34432
title: Wes C Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f7fa'
    - '#000000'
    - '#343f47'
    - '#99adbc'
    - '#697d8c'
  brandStrength: 0.75
  lightness: 0.8534676001872867
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
